# ===========================================================================
# Project:   Habitqueue
# Copyright: ©2011 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore

proxy '/habitqueue', :to => 'localhost:5984'